### ISSUE TITLE
query параметры в href

### ISSUE THREAD

**Issue by sr480** [spec-box/web#2]
https://github.com/spec-box/web/blob/012dadbc9778bab960f5b11f60f9d1ce8f21de68/src/hooks/useRouteLink.ts#L20C3-L20C36

В хуке useRoutLink href создается без query параметров.

`const href = useLink(to, params);`

Fix:
`const href = useLink(to, params, query);`

**Comment by dima117** [comment]
Привет! Пока это было не нужно, но в целом это полезный API
Я добавлю параметры в ближайшее время. Если нужно срочно, то ты можешь прислать PR

**Comment by dima117** [comment]
Починили
